// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATu8XxoYzP-uSP5_ZbVWPhBc9bwm1YHEk',
    appId: '1:181632620220:web:94df02cf5050bc3545a2b9',
    messagingSenderId: '181632620220',
    projectId: 'catalog-app-7ffee',
    authDomain: 'catalog-app-7ffee.firebaseapp.com',
    storageBucket: 'catalog-app-7ffee.appspot.com',
    measurementId: 'G-Y44Q3G9CRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSPH1RL8KW0bFynWM89efCzxayJkwqWQg',
    appId: '1:181632620220:android:cb69ec5ffc4b722a45a2b9',
    messagingSenderId: '181632620220',
    projectId: 'catalog-app-7ffee',
    storageBucket: 'catalog-app-7ffee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBpGXjwVm15IOLMnW_FIClqMy5_6k5K-Y',
    appId: '1:181632620220:ios:9910de5a3d42136e45a2b9',
    messagingSenderId: '181632620220',
    projectId: 'catalog-app-7ffee',
    storageBucket: 'catalog-app-7ffee.appspot.com',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBpGXjwVm15IOLMnW_FIClqMy5_6k5K-Y',
    appId: '1:181632620220:ios:50e9cb0a9321656445a2b9',
    messagingSenderId: '181632620220',
    projectId: 'catalog-app-7ffee',
    storageBucket: 'catalog-app-7ffee.appspot.com',
    iosBundleId: 'com.example.firstproject.RunnerTests',
  );
}
